import { z } from 'zod'

export const FormDataSchema = z.object({
  FirstName: z.string().min(1, 'Your Name is required'),
  LastName: z.string().min(1, 'Your Last Name is required'),
  Email: z.string().min(1, 'Email is required').email('Invalid email address'),
  PhoneNumber: z.string().min(1, 'Your Phone Number is Required'),
  LikeTo: z.string().min(1, 'This field is required'),
  SpecifyType: z.string().min(1, 'Type is required'),
  SpecifyRegion: z.string().min(1, 'Region is required'),
  Country: z.string().min(1, 'Country is required'),
  District: z.string().min(1, 'District is required'),
  GovernateOrState : z.string().min(1, 'Governate or State is required'),
  Financials: z.string().min(1,'This field is required, please put 0 as minimum value'),
  NatureAndLocation: z.string().min(1,'This field is required'),
  CeilingHeightInMeters: z.string().min(1,'This field is required, please put 0 as minimum value'),
  AreaDesiredInSqm: z.string().min(1,'This field is required, please put 0 as minimum value'),
  Lounge: z.boolean(),
  WaitingRoom : z.boolean(),
  Bathrooms: z.boolean(),
  Office: z.boolean(),
  SecretaryOffice: z.boolean(),
  Reception: z.boolean(),
  OtherAreaAndFacilities : z.string(),
  WidthOfEntranceInMeters: z.string().min(1,'This field is required, please put 0 as minimum value'),
  Ramp : z.boolean(),
  Stairs : z.boolean(),
  Elevator: z.boolean(),
  CommodityElevator: z.boolean(),
  Escalator: z.boolean(),
  OtherDetails:z.string(),
  honeypot: z.string(),
})
