import { z } from 'zod'

export const FormDataSchema = z.object({
  FirstName: z.string().min(1, 'Your Name is required'),
  LastName: z.string().min(1, 'Your Last Name is required'),
  Email: z.string().min(1, 'Email is required').email('Invalid email address'),
  PhoneNumber: z.string().min(1, 'Your Phone Number is Required'),
  LikeTo: z.string().min(1, 'This field is required'),
  SpecifyType: z.string().min(1, 'Type is required'),
  SpecifyRegion: z.string().min(1, 'Region is required'),
  Country: z.string().min(1, 'Country is required'),
  District: z.string().min(1, 'District is required'),
  GovernateOrState : z.string().min(1, 'Governate or State is required'),
  LivableArea: z.string().min(1,'This field is required, please put 0 as minimum value'),
  PriceRangeMax: z.string().min(1,'This field is required, please put 0 as minimum value'),
  BedRoomsMin: z.string().min(1,'This field is required, please put 0 as minimum value'),
  BathRoomsMin: z.string().min(1,'This field is required, please put 0 as minimum value'),
  DesiredFloor: z.string().min(1,'This field is required, please put 0 as minimum value'),
  NumberOfSalons: z.string().min(1,'This field is required, please put 0 as minimum value'),
  NumberOfLivingRooms: z.string().min(1,'This field is required, please put 0 as minimum value'),
  NumberOfBathrooms: z.string().min(1,'This field is required, please put 0 as minimum value'),
  NumberOfDiningRooms: z.string().min(1,'This field is required, please put 0 as minimum value'),
  MaidRoomWithBathroom: z.boolean(),
  StorageRoom: z.string().min(1,'This field is required, please put 0 as minimum value'),
  WaterWell:z.boolean(),
  Generator: z.boolean(),
  NumberOfParkingLots: z.string().min(1,'This field is required, please put 0 as minimum value'),
  OtherHomeSize: z.string(),
  CloseToWork: z.boolean(),
  CloseToSchool: z.boolean(),
  CloseToHospital: z.boolean(),
  CloseToSupermarket: z.boolean(),
  CloseToParksRecreation: z.boolean(),
  CloseToRestaurants: z.boolean(),
  CloseToHighways: z.boolean(),
  PublicTransportation: z.boolean(),
  OtherLocation: z.string(),
  NoTraffic: z.boolean(),
  VeryQuiet: z.boolean(),
  YoungerNeighbors: z.boolean(),
  OlderNeighbors: z.boolean(),
  ChildFriendly: z.boolean(),
  OtherNeighborhood: z.string(),
  CloseToHome: z.boolean(),
  GoodReputation: z.boolean(),
  SmallClassSize: z.boolean(),
  SolidCurriculum: z.boolean(),
  OtherSchools: z.string(),
  CentralAC: z.boolean(),
  WoodStove: z.boolean(),
  Fireplace: z.boolean(),
  TanklessWaterHeater: z.boolean(),
  CopperPlumbing: z.boolean(),
  SolarPower: z.boolean(),
  SecuritySystem: z.boolean(),
  HomeAutomation: z.boolean(),
  Cable: z.boolean(),
  SatelliteDish: z.boolean(),
  FiberOpticCable: z.boolean(),
  OtherHomeSystems: z.string(),
  Garage: z.boolean(),
  WalkOutBasement: z.boolean(),
  Driveway: z.boolean(),
  FencedYard: z.boolean(),
  Gardens: z.boolean(),
  Pool: z.boolean(),
  OtherHomeFeaturesExterior: z.string(),
  WoodFlooring: z.boolean(),
  MaidRoom: z.boolean(),
  LaundryRoom: z.boolean(),
  FinishedBasement: z.boolean(),
  EatInKitchen: z.boolean(),
  GameRoom: z.boolean(),
  Office: z.boolean(),
  MasterBedroom: z.boolean(),
  MasterBathroom: z.boolean(),
  WalkInCloset: z.boolean(),
  OtherHomeFeaturesInterior: z.string(),
  honeypot: z.string()
})
